services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Schedule_app_CMBT
    environment:
      - DATABASE_URL="postgresql://postgres:12191980@host.docker.internal:5432/schedcmbtdev"
      - SESSION_SECRET=4D1D5l0O6FS5PevmP/uOow1D3DdYki40qTj1lKvbbgA=
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: "schedcmbtdev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
